name: Check Pull Request
on:
  pull_request:
    types:
      - "opened"

jobs:
  test: 
    name: Release package    
    runs-on: ubuntu-latest
    container: node:16.17.0
    steps:
    - run: yarn install && yarn lint

